"""Build the v1.1 safety corpus only in the canonical Ubuntu GitHub workflow."""

from __future__ import annotations

import argparse
import importlib.metadata
import os
import platform
import shutil
import subprocess
import sys
import tempfile
from datetime import UTC, datetime
from pathlib import Path

from data.canonical_io import canonical_json_bytes
from data.generators.tier_c import (
    DATASET_VERSION,
    MANIFEST_SCHEMA,
    _publish_fresh_tree,
    build_tier_c,
)
from data.safety_corpus import (
    CORPUS_SCHEMA,
    EXPECTED_UBUNTU,
    INVENTORY_NAME,
    PROVENANCE_NAME,
    RELEASE_LINE,
    SAFETY_COUNT,
    SAFETY_DATASET,
    SAFETY_SPLIT,
    SafetyCorpusProvenance,
    current_font_identities,
    inventory_bytes,
    inventory_pin_bytes,
    load_built_safety_corpus,
    parse_inventory_pin,
)
from data.tier_c_contract import (
    TierCContractError,
    VerifiedCanonicalSplit,
    canonical_manifest_bytes,
    default_logical_freeze_path,
    load_verified_generated_split,
    sha256_file,
    verify_logical_freeze,
)
from src.paths import REPO_ROOT

REPOSITORY_IDENTITY = "JoaoMiltzarek/security-shift-intake"
BUILD_WORKFLOW_FILE = "build-safety-corpus.yml"


def _command_output(args: list[str]) -> str:
    try:
        completed = subprocess.run(
            args,
            cwd=REPO_ROOT,
            check=True,
            capture_output=True,
            text=True,
            encoding="utf-8",
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        raise TierCContractError(f"canonical builder command failed: {args[0]}") from exc
    return completed.stdout.strip()


def _os_release(path: Path = Path("/etc/os-release")) -> dict[str, str]:
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError as exc:
        raise TierCContractError("canonical builder requires /etc/os-release") from exc
    values: dict[str, str] = {}
    for line in lines:
        if not line or line.startswith("#"):
            continue
        key, separator, value = line.partition("=")
        if not separator or key in values:
            raise TierCContractError("canonical builder found invalid /etc/os-release")
        values[key] = value.strip().strip('"')
    return values


def require_canonical_builder_environment() -> dict[str, str]:
    """Reject every environment except the manual Ubuntu 24.04 GitHub workflow."""
    release = _os_release()
    required_env = (
        "GITHUB_REPOSITORY",
        "GITHUB_WORKFLOW_REF",
        "GITHUB_SHA",
        "GITHUB_RUN_ID",
        "GITHUB_RUN_ATTEMPT",
        "ImageOS",
        "ImageVersion",
    )
    if (
        os.environ.get("GITHUB_ACTIONS") != "true"
        or os.environ.get("RUNNER_OS") != "Linux"
        or release.get("ID") != "ubuntu"
        or release.get("VERSION_ID") != EXPECTED_UBUNTU
        or any(not os.environ.get(name) for name in required_env)
    ):
        raise TierCContractError(
            "canonical safety corpus may only be built by the manual Ubuntu 24.04 workflow"
        )
    if os.environ["GITHUB_REPOSITORY"] != REPOSITORY_IDENTITY:
        raise TierCContractError("canonical safety corpus repository identity is invalid")
    return release


def require_canonical_builder_workflow() -> None:
    """Require the exact manual event and workflow that may publish corpus artifacts."""
    github_ref = os.environ.get("GITHUB_REF", "")
    expected_workflow_ref = (
        f"{REPOSITORY_IDENTITY}/.github/workflows/{BUILD_WORKFLOW_FILE}@{github_ref}"
    )
    workflow_ref = os.environ.get("GITHUB_WORKFLOW_REF", "")
    if (
        os.environ.get("GITHUB_EVENT_NAME") != "workflow_dispatch"
        or not github_ref
        or workflow_ref != expected_workflow_ref
    ):
        raise TierCContractError(
            "canonical safety corpus requires workflow_dispatch from build-safety-corpus.yml"
        )


def _package_version(package: str) -> str:
    return _command_output(["dpkg-query", "-W", "-f=${Version}", package])


def _environment(name: str) -> str:
    return os.environ[name]


def collect_provenance(
    verified: VerifiedCanonicalSplit, release: dict[str, str]
) -> SafetyCorpusProvenance:
    """Collect and validate all identities that can change generated bytes."""
    commit = _command_output(["git", "rev-parse", "HEAD"])
    uv_output = _command_output(["uv", "--version"])
    uv_version = uv_output.removeprefix("uv ").strip()
    tesseract_line = _command_output(["tesseract", "--version"]).splitlines()[0]
    languages = set(_command_output(["tesseract", "--list-langs"]).splitlines())
    if "por" not in languages:
        raise TierCContractError("canonical builder requires the Portuguese Tesseract language")
    return SafetyCorpusProvenance.model_validate(
        {
            "corpus_schema": CORPUS_SCHEMA,
            "release_line": RELEASE_LINE,
            "dataset": SAFETY_DATASET,
            "split": SAFETY_SPLIT,
            "count": SAFETY_COUNT,
            "dataset_version": DATASET_VERSION,
            "manifest_schema": MANIFEST_SCHEMA,
            "manifest_sha256": verified.manifest_sha256,
            "generator_commit": commit,
            "generated_meta_commit": verified.meta.git_commit,
            "created_at_utc": datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ"),
            "python_version": platform.python_version(),
            "uv_version": uv_version,
            "pillow_version": importlib.metadata.version("pillow"),
            "uv_lock_sha256": sha256_file(REPO_ROOT / "uv.lock"),
            "ubuntu_id": release["ID"],
            "ubuntu_version": release["VERSION_ID"],
            "runner_image": _environment("ImageOS"),
            "runner_image_version": _environment("ImageVersion"),
            "tesseract_package_version": _package_version("tesseract-ocr"),
            "tesseract_por_package_version": _package_version("tesseract-ocr-por"),
            "tesseract_engine_version": tesseract_line.removeprefix("tesseract ").strip(),
            "tesseract_language": "por",
            "github_repository": _environment("GITHUB_REPOSITORY"),
            "github_workflow_ref": _environment("GITHUB_WORKFLOW_REF"),
            "github_sha": _environment("GITHUB_SHA"),
            "github_run_id": _environment("GITHUB_RUN_ID"),
            "github_run_attempt": _environment("GITHUB_RUN_ATTEMPT"),
            "font_files": [font.model_dump(mode="json") for font in current_font_identities()],
        }
    )


def _copy_verified_payload(
    generated: Path,
    staged: Path,
    verified: VerifiedCanonicalSplit,
    provenance: SafetyCorpusProvenance,
) -> None:
    if len(verified.entries) != SAFETY_COUNT:
        raise TierCContractError(
            f"canonical safety split has {len(verified.entries)} sheets, expected {SAFETY_COUNT}"
        )
    (staged / "pngs").mkdir(parents=True)
    (staged / "gt").mkdir()
    (staged / "manifests").mkdir()
    for entry in verified.entries:
        shutil.copyfile(generated / entry.image, staged / entry.image)
        shutil.copyfile(generated / entry.gt, staged / entry.gt)
    (staged / "manifests" / f"{SAFETY_SPLIT}.jsonl").write_bytes(
        canonical_manifest_bytes(verified.entries)
    )
    (staged / "meta.json").write_bytes(
        canonical_json_bytes(verified.meta.model_dump(mode="json"), pretty=True)
    )
    (staged / PROVENANCE_NAME).write_bytes(
        canonical_json_bytes(provenance.model_dump(mode="json"), pretty=True)
    )
    hashes = {
        path.relative_to(staged).as_posix(): sha256_file(path)
        for path in staged.rglob("*")
        if path.is_file()
    }
    (staged / INVENTORY_NAME).write_bytes(inventory_bytes(hashes))


def publish_corpus(
    generated: Path,
    output: Path,
    verified: VerifiedCanonicalSplit,
    provenance: SafetyCorpusProvenance,
) -> None:
    """Assemble, authenticate, and publish a fresh 45-sheet artifact tree."""
    destination = output.expanduser().absolute()
    destination.parent.mkdir(parents=True, exist_ok=True)
    staged = Path(tempfile.mkdtemp(prefix=f".{destination.name}.staging-", dir=destination.parent))
    try:
        _copy_verified_payload(generated, staged, verified, provenance)
        load_built_safety_corpus(staged)
        _publish_fresh_tree(staged, destination)
    finally:
        if staged.exists():
            shutil.rmtree(staged)


def publish_inventory_pin(corpus: Path, output: Path) -> None:
    """Create the external inventory pin once and never place it in the corpus tree."""
    corpus_root = corpus.expanduser().absolute().resolve(strict=False)
    destination = output.expanduser().absolute().resolve(strict=False)
    if destination == corpus_root or destination.is_relative_to(corpus_root):
        raise TierCContractError("external inventory pin must stay outside the corpus tree")
    try:
        content = inventory_pin_bytes(sha256_file(corpus_root / INVENTORY_NAME))
        destination.parent.mkdir(parents=True, exist_ok=True)
        with destination.open("xb") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
    except FileExistsError as exc:
        raise TierCContractError(f"external inventory pin already exists: {destination}") from exc
    except OSError as exc:
        raise TierCContractError("external inventory pin could not be published") from exc
    if parse_inventory_pin(destination.read_bytes()) != sha256_file(corpus_root / INVENTORY_NAME):
        raise TierCContractError("external inventory pin verification failed")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Build the canonical v1.1 safety corpus.")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--inventory-pin-output", type=Path, required=True)
    args = parser.parse_args(argv)
    try:
        release = require_canonical_builder_environment()
        require_canonical_builder_workflow()
        with tempfile.TemporaryDirectory(prefix="ssi-safety-source-") as temporary:
            generated = Path(temporary) / "tier_c"
            build_tier_c(generated, dataset=SAFETY_DATASET)
            verified = load_verified_generated_split(
                generated,
                SAFETY_DATASET,
                SAFETY_SPLIT,
            )
            logical_freeze = default_logical_freeze_path(SAFETY_DATASET, SAFETY_SPLIT)
            if logical_freeze is None:
                raise TierCContractError("logical safety freeze path is not configured")
            verify_logical_freeze(
                verified.entries,
                logical_freeze,
                expected_split=SAFETY_SPLIT,
            )
            provenance = collect_provenance(verified, release)
            publish_corpus(generated, args.output, verified, provenance)
            publish_inventory_pin(args.output, args.inventory_pin_output)
    except (OSError, TierCContractError, ValueError) as exc:
        print(f"SAFETY CORPUS REFUSED: {exc}", file=sys.stderr)
        return 1
    print(
        f"Safety corpus built: {SAFETY_COUNT} sheets, "
        f"manifest={provenance.manifest_sha256}, output={args.output}, "
        f"inventory_pin={args.inventory_pin_output}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
